"""Turn mcqs/*.json into site/data.js — a compact payload the website loads directly.

Keys are shortened (q/o/a/e/c/n/g) purely to keep the file small; the site reads
them back into full names. Files that produced unusable text are skipped.
"""

import json
import re
from pathlib import Path

ROOT = Path(__file__).parent
IN_DIR = ROOT / "mcqs"
OUT = ROOT / "site" / "data.js"

# CamScanner scan with no reliable text layer — its "questions" are OCR noise
SKIP_FILES = {"QUANT_PRACTISE_BOOK"}
MAX_EXPLANATION = 2000


def tidy(text: str) -> str:
    """The PDFs encode the rupee sign as a backtick; restore it."""
    text = re.sub(r"`\s*(?=[\d.])", "₹", text)
    return re.sub(r"\s+", " ", text).strip()


def usable(q: dict) -> bool:
    if len(q.get("options") or {}) < 2:
        return False
    text = (q.get("question") or "").strip()
    if len(text) < 12:
        return False
    # options that are empty or near-identical are extraction noise
    vals = [v.strip() for v in q["options"].values()]
    return all(vals) and len(set(vals)) > 1


def main():
    OUT.parent.mkdir(exist_ok=True)
    subjects = []
    skipped = 0

    for path in sorted(IN_DIR.glob("*.json")):
        if path.stem in SKIP_FILES:
            print(f"[-] skipping {path.stem} (unreliable source text)")
            continue
        raw = json.loads(path.read_text())
        items = []
        for q in raw:
            if not usable(q):
                skipped += 1
                continue
            letters = sorted(q["options"])
            expl = (q.get("explanation") or "")[:MAX_EXPLANATION]
            expl = tidy(expl) if expl else None
            items.append(
                {
                    "q": tidy(q["question"]),
                    "o": [tidy(q["options"][k]) for k in letters],
                    "k": letters,
                    "a": letters.index(q["answer"]) if q.get("answer") in letters else -1,
                    "e": expl,
                    "c": q.get("chapter") or "",
                    "g": q.get("section") or "",
                    "n": q.get("number"),
                }
            )
        if not items:
            continue
        subjects.append(
            {
                "name": raw[0].get("subject") or path.stem,
                "file": path.stem,
                "questions": items,
            }
        )
        print(f"[+] {path.stem:<32} {len(items):>5} questions")

    payload = {"subjects": subjects}
    OUT.write_text(
        "// generated by build_site_data.py — do not edit\n"
        "window.MCQ_DATA = " + json.dumps(payload, ensure_ascii=False) + ";\n"
    )
    total = sum(len(s["questions"]) for s in subjects)
    size = OUT.stat().st_size / 1_048_576
    print(f"\n{total} questions across {len(subjects)} subjects -> {OUT} ({size:.1f} MB)")
    print(f"{skipped} unusable entries dropped")


if __name__ == "__main__":
    main()
